#same as default but try different preprocessing
experiment_name: "QRF_Direct_Default"
model_type: "qrf"

data:
  targets: ["Headline", "Core"]
  horizons: [3, 6, 9, 12]
  evaluation_scheme: "expanding_window"
  eval_start_date: "2015-01-01"
  retrain_step_months: 3
  data_file: "data_stationary_direct.csv"  #use 2. preprocessed data

model:
  tune_hyperparameters: false
  use_residual_forecasting: false
  forecast_method: "direct" 
  params:
    n_estimators: 500
    min_samples_leaf: 10
    max_features: 0.33
    n_jobs: -1
    random_state: 42